### ISSUE TITLE
TypeError running README.md example via ghci

### ISSUE THREAD

**Issue by cdituri** [frerich/random-derive#1]
Template haskell isn't in my bag of tricks yet so this could just be something I'm overlooking but, regardless, I thought I'd report-back.

Need to keep banging out code so I don't have time to comment further right now but if I find a moment to revisit I'll update with any additional information that I come up with. A preemptive thank you for your work and efforts here!

-dituri

```
$ ghci
GHCi, version 7.8.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
ghci> import System.Random
ghci> import System.Random.TH
ghci> :set -XTemplateHaskell
ghci> data Color = Red | Green | Blue deriving (Enum, Bounded)
ghci> $(deriveRandom ''Color)

<interactive>:6:3:
    Couldn't match type `[Language.Haskell.TH.Syntax.Dec]'
                  with `Language.Haskell.TH.Syntax.Exp'
    Expected type: Language.Haskell.TH.Lib.ExpQ
      Actual type: Language.Haskell.TH.Syntax.Q
                     [Language.Haskell.TH.Syntax.Dec]
    In the expression: deriveRandom ''Color
    In the splice: $(deriveRandom ''Color)
ghci>
```

Note: here's my current module listing  for your reference:

```
C:\Some\User\Path\Goes\Here\Yay >ghc-pkg list | egrep -i " (random|template-haskell|base)-"
    base-4.7.0.1
    template-haskell-2.9.0.0
    random-1.1
    random-derive-0.1.0.0
```

**Comment by frerich** [comment]
I think you're doing everything correctly, but yet there is no issue here: as far as I know, you cannot run Template Haskell "splices" in ghci which results in multiple toplevel declarations (such as new instances being declared) like that: the same issue occurs if you try to use e.g. the `deriveJSON` function from `Data.Aeson.TH`. You can, however, print (or pretty-print) splices and show them which gets you the (somewhat) verbose code which is generated:

``` haskell
Frerichs-MBP:tmp frerich$ ghci
GHCi, version 7.8.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
λ: :set -XTemplateHaskell
λ: import System.Random
λ: import System.Random.TH
λ: import Language.Haskell.TH
λ: data Color = Red | Green | Blue deriving (Enum, Bounded)
λ: putStrLn $(deriveRandom ''Color >>= stringE . pprint)
[..]
instance System.Random.Random Ghci1.Color
    where System.Random.randomR (lo_0,
                                 hi_1) g_2 = (GHC.Enum.toEnum a_3, g'_4)
                                    where (a_3,
                                           g'_4) = System.Random.randomR (GHC.Enum.fromEnum lo_0,
                                                                          GHC.Enum.fromEnum hi_1) g_2
          System.Random.random = System.Random.randomR (GHC.Enum.minBound,
                                                        GHC.Enum.maxBound)
```

If you paste the code you wrote into a file and then load that into `ghci`, you'll see that it loads just fine and you can use the `randomColors` function to get an infinite stream of random colors.

**Comment by cdituri** [comment]
@frerich thanks for following up - you're absolutely correct ... it seems ghci cannot cope with multiple top-level declarations generated from Template Haskell. Nothing to see here: issue closed and rightfully so! :-)
