### ISSUE TITLE
Update version bounds?

### ISSUE THREAD

**Issue by kindaro** [frerich/random-derive#3]
Hello Frerich! Great library! Works just fine!

One small problem is that version bounds are a bit out of date. In particular, `base` of version 4.10 contains many useful updates, and 4.11 is out as well, but this package has 4.9 upper bound. Modern `template-haskell` is also out of range.

As far as I can see, the package actually works with more up to date `base` and `template-haskell` versions. In particular, I use `base-4.10.1.0` `template-haskell-2.12.0.0` and it seems to be alright.

**Comment by frerich** [comment]
Thanks for reminding me of this - it [seems](https://travis-ci.org/frerich/random-derive) that by now, GHC 8.4.1 works, too!
